# Generated by Django 3.0.5 on 2020-04-03 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myManga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapter', models.IntegerField(default=1)),
                ('url', models.TextField(default='')),
                ('Category', models.TextField(default='')),
                ('Author', models.CharField(default='', max_length=50)),
                ('Uploaded_date', models.DateField(default=datetime.datetime(2020, 4, 3, 4, 16, 39, 579137, tzinfo=utc))),
            ],
        ),
    ]
