# Generated by Django 3.0.5 on 2020-04-03 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_auto_20200403_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymanga',
            name='Uploaded_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 7, 12, 1, 897845, tzinfo=utc)),
        ),
    ]
