# Generated by Django 3.0.5 on 2020-04-03 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_auto_20200403_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymanga',
            name='Uploaded_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 7, 24, 6, 143823, tzinfo=utc)),
        ),
    ]
