# Generated by Django 2.2.12 on 2020-04-08 09:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_auto_20200403_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conan',
            fields=[
                ('mymanga_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manga.myManga')),
            ],
            bases=('manga.mymanga',),
        ),
        migrations.AlterField(
            model_name='mymanga',
            name='Uploaded_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 9, 38, 27, 524703, tzinfo=utc)),
        ),
    ]
